# Generated by Django 5.1.6 on 2025-03-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggerprofile',
            name='website',
        ),
    ]
